
version: 2

models:

  - name: raw_ecommerce_orders
    description: "Raw model ingesting orders data"
    columns:
      - name: order_id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
