look_ecommerce_analytics:
  outputs:
    dev:
      dataset: analytics_marts
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: "{{ env_var('SA_KEYFILE_PATH') }}"
      location: US
      method: service-account
      priority: interactive
      project: look-ecommerce-analytics
      threads: 1
      type: bigquery
  target: dev
